### ISSUE TITLE
Hi Nice Idea

### ISSUE THREAD

**Issue by OlegLustenko** [fhelwanger/ocaml-on-windows#12] opened 2017-08-16 08:20 UTC
Hi I have tried ocaml-on-windows, but for some reasons (ocamlmerlin seems not in win PATH's). Merlin wasn't started inside vscode.
What do you think, it's possible to make it work?

It's a big goal to make ReasonML run on windows.
Have you reached success with ReasonML?

Do you need any help?

**Comment by fhelwanger** [comment] 2017-08-16 10:52
Hi, thanks for trying!

Yes, I got reasonml to work on vscode. Actually, the main reason I started this project was to learn reasonml on windows 😄

But, for it to work, I had to do the following:

1. Install the [reason extension](https://marketplace.visualstudio.com/items?itemName=freebroccolo.reasonml) on vscode.

2. Put this inside your vscode settings:

```json
{
  "reason.path.ocamlfind": "ocamlfind.cmd",
  "reason.path.ocamlmerlin": "ocamlmerlin.cmd",
  "reason.path.opam": "opam.cmd",
  "reason.path.rebuild": "rebuild.cmd",
  "reason.path.refmt": "refmt.cmd",
  "reason.path.refmterr": "refmterr.cmd",
  "reason.path.rtop": "rtop.cmd"
}
```

3. Now, there's this https://github.com/freebroccolo/ocaml-language-server/issues/27 that's preventing the extension to work properly on windows. You can fix it manually as I described in https://github.com/fhelwanger/ocaml-on-windows/issues/11#issuecomment-321516901.

I already submitted https://github.com/freebroccolo/ocaml-language-server/pull/29 to fix this. I hope it gets merged soon so I can put proper instructions on this project's README about how to configure your editor.

If it doesn't work for you, try to run `ocamlmerlin -version` on `cmd.exe` to find out if the problem is only in vscode or if merlin didn't get installed correctly.

**Comment by OlegLustenko** [comment] 2017-08-16 11:28
Oh wow :)) thanks for sharing. It works !
I appreciate your help.

Pretty sure your package must be in ReasonML official documentation

**Closed as completed** 2017-08-16 12:45 UTC
